name: build page

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Check out the pull request's source code.
      - name: Checkout source code
        uses: actions/checkout@v2

      # install python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: run python script
        run: |
          python -m pip install --upgrade pip
          python src/builddocs.py

      # git add docs folder and push changes
      # commit messages etc. are handled automatically
      - name:
        uses: EndBug/add-and-commit@v7
        with:
          add: 'build'
          push: true
